version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
