FROM python:3.10-slim-bullseye

WORKDIR /usr/src/app
EXPOSE 5000

RUN apt-get update && apt install -y libpq-dev postgresql-client-common build-essential
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY frontend ./frontend
COPY gps_backend ./gps_backend

CMD exec gunicorn --bind :${PORT=5000} --workers 1 --threads 8 --timeout 0 frontend:server
