version: '3.1'

services:

  db:
    container_name: dsc_database
    image: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    container_name: dsc_adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
